### ISSUE TITLE
Problem with Gladys>3.5 in play.js

### ISSUE THREAD

**Issue by Boimb** [Time-Lords/gladys-voicerss#4]
Hi,
I've faced problems using this module with a fresh install of Gladys.
I had this log 'lame is undefined'.
After checking my conf/rebuild all deps with node-gyp, it was allways there...
So i decided to dig into the code...

I've solved that by modifying /lib/play.js

```
const queue = require('queue');
const fs = require('fs');
const config = require('./config');

// Here
let Speaker = null;
let lame = null;


if(config.soundCapable){
// And here too
  Speaker = require('speaker');
  lame = require('lame');
}
else {
console.log('A config problem has been detected... config.SoundCapable = false');
}
// Nothing changed after that...
```
It seems to be a closure prob.
I really don't know if there will be side effects with this so i didn't PR ...
But for now, it solved my issue.
Let me now if u encountered the same and/or you see side effects.
Nevertheless, nice module and great work !
Thx for sharing it.
Cy@.

**Comment by Time-Lords** [comment]
Hello,

Fixed. Thx for report.
